# Generated by Django 3.1.5 on 2021-02-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilchart',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('song', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bilchart',
                'managed': False,
            },
        ),
    ]
