# Generated by Django 3.1.5 on 2021-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilchart',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('song', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bilchart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
