# Generated by Django 3.1.5 on 2021-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
